version: "3.9"

services:
  web-horses:
    image: martinlaizg/web-horses:latest
    container_name: web-horses
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - orders-data:/app/backend/data
    restart: unless-stopped

volumes:
  orders-data:
